import Head from "next/head";
import MainLayout from "components/MainLayout";
import type { NextPage } from "next";
import IntroBanner from "components/Sections/IntroBanner";
import QuestionBanner from "components/Sections/QuestionBanner";
import ListCars from "components/Sections/ListCar";
import listCars from "__mocks__/cars.json";
import HowItWorks from "components/Sections/HowItWorks";
import FeatureVehicle from "components/Sections/FeatureVehicle";
const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>UCARS - Car Marketplace</title>
        <meta name="description" content="Generated by Fetch" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
      </Head>

      <main className="justify-start items-center h-min mx-auto overflow-hidden">
        <IntroBanner />
        <ListCars cars={listCars} />
        <HowItWorks />
        <FeatureVehicle />
        <QuestionBanner />
      </main>
    </MainLayout>
  );
};
export default Home;
