import Head from "next/head";
import MainLayout from "components/MainLayout";
import type { NextPage } from "next";
import IntroBanner from "components/Sections/IntroBanner";
import QuestionBanner from "components/Sections/QuestionBanner";
import ListCars from "components/Sections/ListCar";
import listCars from "__mocks__/cars.json";
import HowItWorks from "components/Sections/HowItWorks";
import FeatureVehicle from "components/Sections/FeatureVehicle";
const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>UCARS - Car Marketplace</title>
        <meta name="description" content="Generated by Fetch" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="justify-start items-center h-min mx-auto overflow-hidden">
        <IntroBanner />
        <ListCars cars={listCars} />
        <HowItWorks />
        <FeatureVehicle/>
        <QuestionBanner />
      </main>
    </MainLayout>
  );
};
export default Home;
